typography_spectrum: 0.42721409583464265
color:
  brandColors:
    - '#f6f1ed'
    - '#d5ccc5'
    - '#814825'
    - '#b69a83'
    - '#26140a'
  brandStrength: 0.0625
  lightness: 0.5625
  saturation: 0.6875
  rhythmicContrast: 0.75
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.22812372958287597
analytics:
  google: UA-77364116-1
  facebook: null
  twitter: null
name: Passion for Sales Management
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: >-
      Why a too strong alignment of marketing- and sales departments could hurt
      the company
    id: 71c750f0-81fc-4485-ab97-7fcee0e2c829
    type: content
favicon: null
title: Passion for Sales Management and research
purpose: []
