layout_spectrum: 0.22812372958287597
typography_spectrum: 0.7084202338010073
color:
  brandColors:
    - '#f6f1ed'
    - '#d5ccc5'
    - '#814825'
    - '#b69a83'
    - '#26140a'
  brandStrength: 0.0625
  lightness: 0.5625
  saturation: 0.6875
  rhythmicContrast: 0.75
opengraph:
  image: null
  type: null
  appId: null
analytics:
  google: UA-77364116-1
  facebook: null
  twitter: null
author:
  name: Erik Mehl
  email: erik.mehl@kristiania.no
name: Passion for Sales Management
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: Passion for Sales Management and research
description: Research on sales
purpose: []
