name: Passion for Sales Management
favicon: null
layout_spectrum: 1
typography_spectrum: 0.83681
title: Passion for Sales Management and research
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-77364116-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f6f1ed'
    - '#d5ccc5'
    - '#814825'
    - '#b69a83'
    - '#26140a'
  brandStrength: 0.0625
  lightness: 0.5625
  saturation: 0.6875
  rhythmicContrast: 0.75
purpose: []
