name: Passion for Sales Management
favicon: null
layout_spectrum: 0.90612
typography_spectrum: 1
title: Passion for Sales Management and research
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f6f1ed'
    - '#d5ccc5'
    - '#814825'
    - '#b69a83'
    - '#26140a'
  brandStrength: 0
  lightness: 0.375
  saturation: 0.75
  rhythmicContrast: 0.75
purpose: []
